### ISSUE TITLE
Some keyword will match entry ignoring locationSet

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5669]
For example, when I want to add a `KFC` in China

(You can see the location in url)

![图片](https://user-images.githubusercontent.com/42690037/140754018-6fa662d3-c24b-458b-9b06-a4d2f8d24ec5.png)

it give me several country's KFC preset, but some of them shouldn't appare in China, for example:

https://github.com/osmlab/name-suggestion-index/blob/e39f7223a8d068e0a82b6fb6ab1fe15092448c77/data/brands/amenity/fast_food.json#L6876-L6886

**Comment by UKChris-osm** [comment]
I just tried that location and was only offered two KFC entries. Is this bug still occurring @LaoshuBaby 

I'm also wondering if the global KFC should have locationSet exclusions to stop two KFC suggestions popping up for the same location?

![kfc](https://user-images.githubusercontent.com/59393694/140817396-30f9b851-3bce-41f8-b0ed-9df8e07be792.png)

**Comment by arch0345** [comment]
I think this has been fixed - I reproduced this issue a couple hours after this ticket was created, but as you've shown now only those two show up when you search for KFC.

**Comment by arch0345** [comment]
I'll exclude the countries that have their own regional entry for the global entry

**Comment by bhousel** [comment]
> I'm also wondering if the global KFC should have locationSet exclusions to stop two KFC suggestions popping up for the same location?

Just catching up on the discussion - yes, if we excluded the local regions from the global one, it should fix the issue of there being a mix of global and regional presets to choose from.  

The "upgrade tags" validator should be smart enough to pick the more local item over the global one, but the preset system pictured here doesn't have that kind of logic built into it.

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/141151083-ff968af6-c237-41e1-a8b7-0094111f0cc4.png)

> I just tried that location and was only offered two KFC entries. Is this bug still occurring @LaoshuBaby

@UKChris-osm 

I can reproduce this problem on another tablet

Maybe this is because my browser's locale? My browser’s preferred language is zh-CN

**What I want to complain isn‘t global one, but the Arabic one and Japanese one. Those 2 entry hadn't include China, but they are still suggested.**

**Comment by bhousel** [comment]
@LaoshuBaby I agree these shouldn't show up here - ("Kerala Financial Corporation" shouldn't either - it's an Indian financial office)

Can you open the developer tools for this browser (looks like Edge?) and let me know if there are any errors reported?  I'm wondering if the location file could not be fetched so they are all being treated as global brands for you.

**Comment by arch0345** [comment]
I don't think it's your locale as I can also reproduce this with an en-US locale. The only error I found was due to my adblocker, but when I disabled it, the issue still persists.
![image](https://user-images.githubusercontent.com/85302075/141153973-a6d9a33c-b791-48c4-ad92-69b7e9aa25c8.png)
![image](https://user-images.githubusercontent.com/85302075/141154463-f80f9e1d-7282-425c-aad7-078ffb6d0ded.png)

**Comment by LaoshuBaby** [comment]
> Can you open the developer tools for this browser (looks like Edge?) and let me know if there are any errors reported? I'm wondering if the location file could not be fetched so they are all being treated as global brands for you.

![图片](https://user-images.githubusercontent.com/42690037/141154274-455a1557-e61f-4a75-85a5-af69b1e7c2a0.png)

Maybe this can help?

Looks like some AD block plugin in Firefox have wrong thing(that day I also use Firefox)

So I try Edge to reproduce,but
![图片](https://user-images.githubusercontent.com/42690037/141154838-c339eb8d-fec9-43ef-a27c-b5bf6582c8f4.png)

---

My net is slow so when I post this comment I noticed @arch0345  have the same action and idea with me, thanks!

**Comment by LaoshuBaby** [comment]
Besides, the error in edge is too long , and it continue to occur, again and again, even slow my computer

**Comment by bhousel** [comment]
I'm also having trouble reproducing the issue.. I see this in Chrome on both RapiD and iD:

https://www.openstreetmap.org/edit#map=18.5/39.96491/116.32973
https://mapwith.ai/rapid#map=18.5/39.96491/116.32973

<img width="300" alt="Screen Shot 2021-11-10 at 12 58 56 PM" src="https://user-images.githubusercontent.com/38784/141167606-a9712a1d-f07d-46f0-8918-5355bd5ae4f9.png">

But there's a catch - the preset list can only filter the presets after their locations have been indexed, so if I try to add a point immediately at startup (like within the first 1-5 seconds), I do see the full list:

<img width="300" alt="Screen Shot 2021-11-10 at 1 00 35 PM" src="https://user-images.githubusercontent.com/38784/141167862-bf4509f4-1a75-4c0f-9d10-34968386e71f.png">

So I wonder if theres something in that indexing process that's failing or just taking very long in some cases.

**Comment by LaoshuBaby** [comment]
![Screenshot_2021-11-11-02-24-43-258_mark via](https://user-images.githubusercontent.com/42690037/141171572-b09366b7-da8c-4eb3-9361-94054d6b38eb.jpg)

I'm confused too.
This time I use a Android mobile phone……slow enough (even typing a word need some second)……but the problem don't occur……
